LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := LogFox
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := LogFox/LogFox.apk
LOCAL_OVERRIDES_PACKAGES := MatLog
include $(BUILD_PREBUILT)
